spring.application.name=games_collection

spring.datasource.url=jdbc:postgresql://localhost:5432/central_videogames
spring.datasource.username=postgres
spring.datasource.password=wingardium

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,beans,mappings,env